cash: #order matters.
  hundred:
    label: 'ONE HUNDRED'
    amount: 100.0
  twenty:
    label: 'TWENTY'
    amount: 20.0
  ten:
    label: 'TEN'
    amount: 10.0
  five:
    label: 'FIVE'
    amount: 5.0
  one:
    label: 'ONE'
    amount: 1.0
  quarter:
    label: 'QUARTER'
    amount: 0.25
  dime:
    label: 'DIME'
    amount: 0.10
  nickel:
    label: 'NICKEL'
    amount: 0.05
  penny:
    label: 'PENNY'
    amount: 0.01
initial:
  hundred: 2
  twenty: 2
  ten: 2
  five: 2
  one: 2
  quarter: 5
  dime: 5
  nickel: 5
  penny: 10
